version: "3"
services:
  ipfs:
    build:
      context: .
      # args:
      #   - IPFS_PLUGINS=sdspfs.so
    entrypoint: tail -f /dev/null
    volumes:
      - ipfs_volume:/data/ipfs
      - ipfs_fuse:/ipfs
      - ipns_fuse:/ipns
    ports:
      - "0.0.0.0:4001:4001"
      - "0.0.0.0:4001:4001/udp"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"
    logging:
      driver: "json-file"
      options:
        max-size: "512m"

volumes:
  ipfs_volume:
  ipfs_fuse:
  ipns_fuse:
